Controllers/WalletController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using iParking.Data;
using iParking.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace iParking.Controllers
{
    [Authorize]
    public class WalletController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public WalletController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }
        public IActionResult Fill() => View();

        [HttpPost]
        public async Task<IActionResult> Fill(WalletFillModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var wallet =  _context.Wallets.FirstOrDefault(f => f.UserId == userId);

                if(wallet == null)
                {
                    wallet = _context.Wallets.Add(new UserWallet
                    {
                        UserId = userId
                    }).Entity;

                    await _context.SaveChangesAsync();
                }

                wallet.Amount += model.Amount;
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }
    }
}

Views/Shared/CreditCardPartial.cshtml
@model WalletFillModel
<fieldset>
    <legend>Payment</legend>
    <div class="form-group">
        <label class="col-sm-4 control-label" asp-for="CardOwner"></label>
        <div class="col-sm-8">
            <input class="form-control" asp-for="CardOwner" placeholder="Card Holder's Name">
            <span asp-validation-for="CardOwner" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-4 control-label" asp-for="CardNumber">Număr card</label>
        <div class="col-sm-8">
            <input class="form-control" asp-for="CardNumber" placeholder="Debit/Credit Card Number">
            <span asp-validation-for="CardNumber" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-4 control-label" asp-for="CardExpiryMonth"></label>
        <div class="col-sm-8">
            <div class="row">
                <div class="col-xs-6">
                    <select class="form-control col-sm-2" asp-for="CardExpiryMonth">
                        <option>Month</option>
                        <option value="01">Jan (01)</option>
                        <option value="02">Feb (02)</option>
                        <option value="03">Mar (03)</option>
                        <option value="04">Apr (04)</option>
                        <option value="05">Mai (05)</option>
                        <option value="06">Iunie (06)</option>
                        <option value="07">Iulie (07)</option>
                        <option value="08">Aug (08)</option>
                        <option value="09">Sep (09)</option>
                        <option value="10">Oct (10)</option>
                        <option value="11">Noi (11)</option>
                        <option value="12">Dec (12)</option>
                    </select>
                    <span asp-validation-for="CardExpiryMonth" class="text-danger"></span>
                </div>
                <div class="col-xs-6">
                    <select class="form-control" asp-for="CardExpiryYear">
                        <option value="13">2013</option>
                        <option value="14">2014</option>
                        <option value="15">2015</option>
                        <option value="16">2016</option>
                        <option value="17">2017</option>
                        <option value="18">2018</option>
                        <option value="19">2019</option>
                        <option value="20">2020</option>
                        <option value="21">2021</option>
                        <option value="22">2022</option>
                        <option value="23">2023</option>
                    </select>
                    <span asp-validation-for="CardExpiryYear" class="text-danger"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-4 control-label" asp-for="CVV"></label>
        <div class="col-sm-8">
            <input class="form-control" asp-for="CVV" placeholder="Security Code">
            <span asp-validation-for="CVV" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-4 col-sm-9">
            <button type="submit" class="btn btn-primary">Suplinește cont</button>
        </div>
    </div>
</fieldset>

Views/Shared/_AdminLayout.cshtml
@using iParking.Services
@using Microsoft.AspNetCore.Identity
@using iParking.Models

@inject IWalletService _walletService
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    string amount = _walletService.GetCurrentAmount(User);
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - iParking</title>

    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: #16a085">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Admin" asp-action="Index" class="navbar-brand" style="color: white">iParking</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Admin"))
                    {
                        <li>
                            <a asp-controller="Admin" asp-action="CreateAccount" style="color: white">Creare cont nou</a>
                        </li>
                        <li>
                            <a asp-controller="Admin" asp-action="Index" style="color: white">Parcări</a>
                        </li>
                        <li>
                            <a asp-controller="Admin" asp-action="Reservations" style="color: white">Rezervări</a>
                        </li>
                    }
                </ul>
                @if (SignInManager.IsSignedIn(User))
                {
                    <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#" style="color: white">@UserManager.GetUserName(User)!</a>
                            </li>
                            <li>
                                <button type="submit" class="btn btn-link navbar-btn navbar-link" style="color:white">Ieșire</button>
                            </li>
                        </ul>
                    </form>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Logare</a></li>
                    </ul>
                }
            </div>
        </div>
    </nav>
    <div style="margin-top:10px;" class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
@using iParking.Services
@inject IWalletService _walletService
@{
    string amount = _walletService.GetCurrentAmount(User);
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - iParking</title>

    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">iParking</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-controller="Wallet" asp-action="Fill">@amount <i style="margin-left: 5px;" class="fa fa-plus" aria-hidden="true"></i></a>
                    </li>

                    <li>
                        <a asp-controller="Reservations" asp-action="Index">Rezervările mele</a>
                    </li>
                    <li>
                        <a asp-controller="Reservations" asp-action="Create">Rezervă o parcare</a>
                    </li>
                    @if(User.IsInRole("Admin"))
                    {
                        <li>
                            <a asp-controller="Account" asp-action="CreateAccount">Creare cont nou</a>
                        </li>
                        <li>
                            <a asp-controller="Parkings" asp-action="Index">Parcări</a>
                        </li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div style="margin-top:10px;" class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>